"""Style x size template rows from the harvested winner rosters.

Owner ruling 2026-09-04 ("ok do it", after blind rounds 1 and 2): the
content templates judge every style against the same row, while winning
brawls and winning claps at 20 field measurably different things. This
step turns the evidence board (`audit_style_rosters.py` ->
`out/style_roster_evidence.json`) into `templates/style_bands.yaml`: per
playstyle x size band, a target and soft cap per capability under the
standing convention (target 0.9 x p10, soft cap 1.15 x p90 of the dressed
supply winning rosters field, person units), read by the engine AFTER the
content row for declared styles at 10+ (hard floors stay content facts in
weapon units; `balanced` never reads a band).

Four owner-ruled rules:
  1. a layer BESIDE the content templates, never a replacement;
  2. only cells with >= MIN_DISTINCT distinct rosters carry their own
     numbers — a thin cell BORROWS its nearest filled cell (same style,
     nearest band; else the parent style at the same band) and says so;
  3. the standing convention for the numbers. Engage / mobility /
     knockback_displace / disengage were EXCLUDED at first ("5-11x the
     content targets because every boot carries a claim") and ADMITTED the
     same evening once measured (owner: "go ahead with your
     recommendation"): on 300 winning rosters of 15+ the WEAPON-ONLY
     supply already runs 3-4x the content targets (engage 12.8, mobility
     16.8, knockback 11.3, disengage 8.8 at 20 vs targets of 4.0 / 4.0 /
     3.3 / 6.3) and boots add about a third on top; the published comps
     that fitted those targets carry boots on 509 of 579 slots. The old
     targets are outlier minimums off single comps (the unit re-fit's own
     note), not a kit-claim inflation. EXCLUDED stays as a mechanism, empty.
  4. golden re-pins + tier2 follow; the blind-round loop keeps validating
     the labels these rows are keyed on.

Explicit step, never part of a normal build (like the samplers): rerun it
after a harvest + audit refresh, then rebuild the dataset and run the gates.
A capability whose p90 is zero in a cell gets NO row (the content row
stands) — never invent a number to fill a hole. A capability whose p10 is
zero (a tenth of winning rosters field none) has NO MINIMUM from the
harvest: the row carries the soft cap only and the content target stands
(the engine divides by the target, and zero is not a target).

    py -3 pipeline/derive_style_bands.py
"""
import datetime
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, "out")
EVIDENCE = os.path.join(OUT, "style_roster_evidence.json")
TARGET = os.path.join(HERE, "templates", "style_bands.yaml")

STYLES = ("brawl", "clap", "kite", "brawl_clap", "clap_kite")
BANDS = (("10-14", 10, 14, 12), ("15-19", 15, 19, 17), ("20", 20, 99, 20))
PARENT = {"brawl_clap": "brawl", "clap_kite": "clap"}
MIN_DISTINCT = 40
EXCLUDED = ()   # none since 2026-09-04 (see docstring, rule 3)
TARGET_OF_P10 = 0.9
SOFT_OF_P90 = 1.15


def main():
    if not os.path.exists(EVIDENCE):
        sys.exit("no evidence board - run audit_style_rosters.py first")
    with open(EVIDENCE, encoding="utf-8") as f:
        ev = json.load(f)
    board = ev["board"]
    filled = {k for k, e in board.items() if e["distinct"] >= MIN_DISTINCT}

    def nearest(style, band_key):
        """Same style, nearest band by distance; else the parent style at
        the same band; else the parent style's nearest band."""
        order = [b[0] for b in BANDS]
        i = order.index(band_key)
        by_dist = sorted(order, key=lambda b: abs(order.index(b) - i))
        for st in (style, PARENT.get(style)):
            if not st:
                continue
            for b in by_dist:
                if f"{st}|{b}" in filled:
                    return f"{st}|{b}"
        return None

    lines = [
        "# Style x size template rows - GENERATED by pipeline/derive_style_bands.py",
        f"# from out/style_roster_evidence.json (board generated {ev.get('_generated')},",
        f"# {ev.get('rosters_total')} harvested killer-party rosters of 10+, labelled by",
        "# comp_identity, supply measured dressed in person units). Do not hand-edit:",
        "# rerun the audit, then this script. Owner ruling 2026-09-04 (four parts, see",
        "# the script docstring and tests/VALIDATION.md 'Style x band rows').",
        "#",
        "# Read by the engine AFTER the content row, for a DECLARED style at 10+:",
        "# target/soft_cap replace the content template's for the capabilities",
        "# listed, scaled linearly from ref_size (person units, like the content",
        "# rows since the 2026-08-29 unit re-fit). Hard floors are untouched",
        "# (weapon units, content facts); weights are untouched (styles.yaml);",
        "# `balanced` never reads a band. A capability absent from a cell keeps the",
        "# content row - a zero p90 is 'we do not know', never a number; a zero",
        "# p10 (no minimum from the harvest) writes the soft cap only and the",
        "# content target stands.",
        f"# Convention: target = {TARGET_OF_P10} x p10, soft_cap = {SOFT_OF_P90} x p90.",
        f"# Cells with fewer than {MIN_DISTINCT} distinct rosters borrow their nearest",
        "# filled cell (same style, nearest band; else the parent style) - stated per",
        f"# cell as `borrowed_from`. Excluded capabilities: "
        f"{', '.join(EXCLUDED) if EXCLUDED else 'none (the 2026-09-04 movement exclusion was lifted the same day once measured)'}.",
        "",
        "min_size: 10",
        f"convention: {{target_of_p10: {TARGET_OF_P10}, soft_of_p90: {SOFT_OF_P90}, min_distinct: {MIN_DISTINCT}}}",
        f"excluded: [{', '.join(EXCLUDED)}]",   # empty list when nothing is excluded
        "",
        "bands:",
    ]
    summary = []
    for style in STYLES:
        lines.append(f"  {style}:")
        for band_key, lo, hi, ref in BANDS:
            key = f"{style}|{band_key}"
            src = key if key in filled else nearest(style, band_key)
            if src is None:
                lines.append(f"    # {band_key}: no filled cell to borrow - content row stands")
                continue
            e = board[src]
            src_ref = e["size_ref"]
            lines.append(f"    \"{band_key}\":")
            lines.append(f"      sizes: [{lo}, {hi}]")
            lines.append(f"      ref_size: {src_ref}")
            lines.append(f"      distinct: {e['distinct']}")
            if src != key:
                own = board.get(key, {}).get("distinct", 0)
                lines.append(f"      borrowed_from: \"{src}\"   # own cell: {own} distinct rosters")
            lines.append("      requirements:")
            rows = 0
            for cap in sorted(e["supply"]):
                if cap in EXCLUDED:
                    continue
                s = e["supply"][cap]
                p10, p90 = s.get("p10") or 0.0, s.get("p90") or 0.0
                if p90 <= 0:
                    continue
                target = round(TARGET_OF_P10 * p10, 2)
                soft = round(SOFT_OF_P90 * p90, 2)
                if soft <= target:
                    continue
                p50 = s.get("p50") or 0.0
                if target > 0:
                    lines.append(f"        {cap + ':':<20}{{target: {target:>7.2f}, soft_cap: {soft:>7.2f}}}"
                                 f"   # p10/p50/p90 {p10:.1f}/{p50:.1f}/{p90:.1f}")
                else:
                    lines.append(f"        {cap + ':':<20}{{soft_cap: {soft:>7.2f}}}"
                                 f"   # p10/p50/p90 {p10:.1f}/{p50:.1f}/{p90:.1f}; no minimum, content target stands")
                rows += 1
            summary.append((key, src, e["distinct"], rows))
    with open(TARGET, "w", encoding="utf-8", newline="\n") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {os.path.relpath(TARGET, HERE)}")
    for key, src, n, rows in summary:
        tag = "" if key == src else f"  (borrowed from {src})"
        print(f"  {key:<18} n={n:<4} rows={rows}{tag}")


if __name__ == "__main__":
    main()
